# Render manifest to deploy backend from the 'backend' folder
services:
  - type: web
    name: todo-backend
    runtime: node
    plan: free
    branch: main
    # rootDirectory should point to the folder that contains package.json
    rootDirectory: backend
  # Use commands that run inside the `rootDirectory` (backend)
  buildCommand: npm ci
  startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000

  - type: static
    name: todo-frontend
    runtime: static
    plan: free
    branch: main
    rootDirectory: frontend
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: frontend/build
    # Do not set API URL here; set REACT_APP_API_URL in Vercel or the frontend service env

# Notes:
# - This manifest explicitly directs Render to the `backend` folder so it can
#   find `backend/package.json`. If you still see ENOENT for package.json,
#   confirm that `backend/package.json` exists and that the service is using
#   this manifest (Render reads the root-level render.yaml on deploy).
