# Render manifest to deploy backend from the 'backend' folder
services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: todo-frontend
    env: static
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    # Don't set the API URL here; set REACT_APP_API_URL in the Render dashboard
    # for the frontend service once the backend public URL is available.

# Notes:
# - This manifest tells Render to run build/start inside the 'backend' folder
#   so it finds the backend's package.json. If your service was previously
#   created pointing to another folder, Render will use this manifest on next
#   deploy to set the correct rootDir.
