services:
  - type: web
    name: todo-backend
    runtime: node
    rootDirectory: ./
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
    healthCheckPath: /
    plan: free
    branch: main