services:
  - type: web
    name: todo-backend
    runtime: node
  rootDirectory: .
  buildCommand: npm install
  startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://todo-frontend.vercel.app # Update this with your actual frontend URL
    healthCheckPath: /
    plan: free
    branch: main
    autoDeploy: true